import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Button from '@mui/material/Button';
import back from '../images/img2.jpg'
import logo from '../images/logo.png'
import Icon from '@mui/material/Icon';

import ChevronRightIcon from '@mui/icons-material/ChevronRight';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello Adil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <div className={styles.hero}>
        <nav className={styles.navbar}>
          <div>
        <Image width = "170px" height="56px"   src={logo} alt="logo" />
        </div>
        <div className={styles.flex1}>
         <select className={styles.select}>
           <option hidden selected disabled value="0" className={styles.option}>English</option>
           <option className={styles.option}>العربية</option>
           <option className={styles.option}>Francais</option>
           <option className={styles.option}>English</option>
         </select>
         <Button variant="contained" className={styles.btn1}>Sign In</Button>
         </div>
       </nav>
       <div className={styles.center}>
        <h1>Unlimited movies, TV<br /> shows, and more.</h1>
        <p className={styles.txt}>Watch anywhere. Cancel anytime.</p>
        <p className={styles.text1}>Ready to watch? Enter your email to create or restart your membership.</p>

       </div>
       <div className={styles.btn2}>
        <input type="email" placeholder="Email Address" required className={styles.  input1}/>
        <button>get started <ChevronRightIcon className={styles.icon}/></button>
       </div>
       </div>
     <Link href="about"><a>About</a></Link>

     
     
    </div>
  )
}
